---
# file: roles/pre_deploy/tasks/main.yml

- name: Check to see if parameters.yml exists
  stat: path={{project_gluster_mount}}/app/config/parameters.yml
  register: parameters_yml

- name: Check to see if there has already been a previous deploy
  stat: path={{project_root}}/current
  register: previous_deploy

- name: Create/prepare base directory
  file: state=directory path={{item.path}}
  with_items:
    - { path: "{{project_root}}" }
