---
# file: roles/pre_deploy/tasks/main.yml

- name: Check to see if parameters.yml exists
  stat: path={{project_gluster_mount}}/www/app/config/parameters.yml
  register: parameters_yml

- name: Check to see if there has allready been a previous deploy
  stat: path={{project_root}}/current
  register: previous_deploy

- name: Create/prepare base directory
  file: state=directory path={{item.path}}
  with_items:
    - { path: "{{project_root}}" }

- name: Hubot say started
  shell: cd {{project_root}}/current && php app/console self:gitter "{{ local_user }} has started a new SELF deployment"
  when: inventory_hostname == groups.web[0] and previous_deploy.stat.exists