---
  - hosts: linode-web
    sudo: yes
    gather_facts: false
    vars_files:
      - vars-linode-prod.yml
    roles:
      - pre_deploy

  - hosts: linode-web
    sudo: yes
    gather_facts: false
    vars_files:
      - vars-linode-prod.yml
    roles:
      - webtier

  - hosts: linode-web
    sudo: yes
    gather_facts: false
    vars_files:
      - vars-linode-prod.yml
    roles:
      - post_deploy