---
# file: roles/post_deploy/tasks/main.yml

- name: Unlock website
  shell: cd {{project_root}}/releases/{{project_release}} && php app/console lexik:maintenance:unlock -n

- name: Faye end warning message
  shell: cd {{project_root}}/releases/{{project_release}} && php app/console self:maintenance 0
